-- HireHub initial PostgreSQL schema. This migration is intentionally self-contained
-- so `prisma migrate deploy` works against an empty production database.
CREATE TYPE "SystemRole" AS ENUM ('CANDIDATE','RECRUITER','COMPANY_ADMIN','PLATFORM_ADMIN');
CREATE TYPE "AccountProvider" AS ENUM ('PASSWORD','GOOGLE');
CREATE TYPE "CompanyStatus" AS ENUM ('PENDING','VERIFIED','SUSPENDED');
CREATE TYPE "MemberStatus" AS ENUM ('INVITED','ACTIVE','DISABLED');
CREATE TYPE "JobStatus" AS ENUM ('DRAFT','PUBLISHED','PAUSED','CLOSED','ARCHIVED');
CREATE TYPE "Workplace" AS ENUM ('ONSITE','HYBRID','REMOTE');
CREATE TYPE "EmploymentType" AS ENUM ('FULL_TIME','PART_TIME','CONTRACT','INTERNSHIP');
CREATE TYPE "ApplicationStage" AS ENUM ('APPLIED','SCREENING','INTERVIEW','OFFER','HIRED','REJECTED','WITHDRAWN');
CREATE TYPE "InterviewStatus" AS ENUM ('SCHEDULED','CONFIRMED','RESCHEDULE_REQUESTED','COMPLETED','CANCELLED');
CREATE TYPE "OfferStatus" AS ENUM ('DRAFT','SENT','ACCEPTED','DECLINED','EXPIRED');
CREATE TYPE "SubscriptionPlan" AS ENUM ('FREE','PRO');
CREATE TYPE "SubscriptionStatus" AS ENUM ('ACTIVE','PAST_DUE','CANCELLED','TRIALING');

CREATE TABLE "User" ("id" TEXT PRIMARY KEY,"email" TEXT NOT NULL UNIQUE,"name" TEXT NOT NULL,"passwordHash" TEXT,"role" "SystemRole" NOT NULL,"emailVerifiedAt" TIMESTAMP(3),"deletedAt" TIMESTAMP(3),"suspendedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "AuthAccount" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"provider" "AccountProvider" NOT NULL,"providerAccountId" TEXT NOT NULL,CONSTRAINT "AuthAccount_provider_providerAccountId_key" UNIQUE("provider","providerAccountId"));
CREATE TABLE "Session" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"tokenHash" TEXT NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"revokedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "AuthToken" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"purpose" TEXT NOT NULL,"tokenHash" TEXT NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"consumedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "CandidateProfile" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL UNIQUE,"headline" TEXT,"bio" TEXT,"phone" TEXT,"location" TEXT,"yearsExperience" INTEGER NOT NULL DEFAULT 0,"skills" TEXT[] NOT NULL,"portfolioUrl" TEXT,"privacy" JSONB,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "CandidateExperience" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"company" TEXT NOT NULL,"title" TEXT NOT NULL,"location" TEXT,"startsAt" TIMESTAMP(3) NOT NULL,"endsAt" TIMESTAMP(3),"current" BOOLEAN NOT NULL DEFAULT false,"description" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "CandidateEducation" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"school" TEXT NOT NULL,"degree" TEXT NOT NULL,"field" TEXT,"startsAt" TIMESTAMP(3) NOT NULL,"endsAt" TIMESTAMP(3),"description" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Resume" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"name" TEXT NOT NULL,"objectKey" TEXT NOT NULL,"mimeType" TEXT NOT NULL,"size" INTEGER NOT NULL,"extractedText" TEXT,"isDefault" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Company" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL,"slug" TEXT NOT NULL UNIQUE,"description" TEXT,"logoKey" TEXT,"website" TEXT,"timezone" TEXT NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',"status" "CompanyStatus" NOT NULL DEFAULT 'PENDING',"settings" JSONB NOT NULL DEFAULT '{}',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "CompanyMember" ("id" TEXT PRIMARY KEY,"companyId" TEXT NOT NULL,"userId" TEXT NOT NULL,"role" "SystemRole" NOT NULL,"status" "MemberStatus" NOT NULL DEFAULT 'ACTIVE',"permissions" TEXT[] NOT NULL,CONSTRAINT "CompanyMember_companyId_userId_key" UNIQUE("companyId","userId"));
CREATE TABLE "Invitation" ("id" TEXT PRIMARY KEY,"companyId" TEXT NOT NULL,"email" TEXT NOT NULL,"role" "SystemRole" NOT NULL,"tokenHash" TEXT NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"acceptedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Job" ("id" TEXT PRIMARY KEY,"companyId" TEXT NOT NULL,"title" TEXT NOT NULL,"slug" TEXT NOT NULL,"department" TEXT NOT NULL,"location" TEXT NOT NULL,"workplace" "Workplace" NOT NULL,"employmentType" "EmploymentType" NOT NULL,"description" TEXT NOT NULL,"requirements" TEXT NOT NULL,"salaryMin" INTEGER,"salaryMax" INTEGER,"currency" TEXT NOT NULL DEFAULT 'VND',"status" "JobStatus" NOT NULL DEFAULT 'DRAFT',"deadline" TIMESTAMP(3),"publishedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Job_companyId_slug_key" UNIQUE("companyId","slug"));
CREATE TABLE "JobSkill" ("id" TEXT PRIMARY KEY,"jobId" TEXT NOT NULL,"name" TEXT NOT NULL,"required" BOOLEAN NOT NULL DEFAULT true,CONSTRAINT "JobSkill_jobId_name_key" UNIQUE("jobId","name"));
CREATE TABLE "ScreeningQuestion" ("id" TEXT PRIMARY KEY,"jobId" TEXT NOT NULL,"prompt" TEXT NOT NULL,"required" BOOLEAN NOT NULL DEFAULT true,"position" INTEGER NOT NULL);
CREATE TABLE "SavedJob" ("userId" TEXT NOT NULL,"jobId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY("userId","jobId"));
CREATE TABLE "PipelineStage" ("id" TEXT PRIMARY KEY,"companyId" TEXT NOT NULL,"key" "ApplicationStage" NOT NULL,"label" TEXT NOT NULL,"position" INTEGER NOT NULL,CONSTRAINT "PipelineStage_companyId_key_key" UNIQUE("companyId","key"));
CREATE TABLE "Application" ("id" TEXT PRIMARY KEY,"jobId" TEXT NOT NULL,"candidateId" TEXT NOT NULL,"resumeId" TEXT NOT NULL,"pipelineStageId" TEXT NOT NULL,"assignedMemberId" TEXT,"stage" "ApplicationStage" NOT NULL DEFAULT 'APPLIED',"version" INTEGER NOT NULL DEFAULT 0,"coverLetter" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Application_jobId_candidateId_key" UNIQUE("jobId","candidateId"));
CREATE TABLE "ApplicationAnswer" ("id" TEXT PRIMARY KEY,"applicationId" TEXT NOT NULL,"questionId" TEXT NOT NULL,"answer" TEXT NOT NULL,CONSTRAINT "ApplicationAnswer_applicationId_questionId_key" UNIQUE("applicationId","questionId"));
CREATE TABLE "StageHistory" ("id" TEXT PRIMARY KEY,"applicationId" TEXT NOT NULL,"fromStage" "ApplicationStage","toStage" "ApplicationStage" NOT NULL,"changedById" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "CandidateNote" ("id" TEXT PRIMARY KEY,"applicationId" TEXT NOT NULL,"authorId" TEXT NOT NULL,"body" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Tag" ("id" TEXT PRIMARY KEY,"companyId" TEXT NOT NULL,"name" TEXT NOT NULL,"color" TEXT NOT NULL,CONSTRAINT "Tag_companyId_name_key" UNIQUE("companyId","name"));
CREATE TABLE "ApplicationTag" ("applicationId" TEXT NOT NULL,"tagId" TEXT NOT NULL,PRIMARY KEY("applicationId","tagId"));
CREATE TABLE "Interview" ("id" TEXT PRIMARY KEY,"applicationId" TEXT NOT NULL,"startsAt" TIMESTAMP(3) NOT NULL,"endsAt" TIMESTAMP(3) NOT NULL,"timezone" TEXT NOT NULL,"meetingUrl" TEXT,"status" "InterviewStatus" NOT NULL DEFAULT 'SCHEDULED',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "InterviewParticipant" ("interviewId" TEXT NOT NULL,"memberId" TEXT NOT NULL,PRIMARY KEY("interviewId","memberId"));
CREATE TABLE "Scorecard" ("id" TEXT PRIMARY KEY,"interviewId" TEXT NOT NULL,"authorId" TEXT NOT NULL,"recommendation" TEXT NOT NULL,"score" INTEGER NOT NULL,"notes" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Scorecard_interviewId_authorId_key" UNIQUE("interviewId","authorId"));
CREATE TABLE "Offer" ("id" TEXT PRIMARY KEY,"applicationId" TEXT NOT NULL UNIQUE,"salary" INTEGER NOT NULL,"currency" TEXT NOT NULL DEFAULT 'VND',"startsAt" TIMESTAMP(3) NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"status" "OfferStatus" NOT NULL DEFAULT 'DRAFT',"respondedAt" TIMESTAMP(3));
CREATE TABLE "Conversation" ("id" TEXT PRIMARY KEY,"companyId" TEXT NOT NULL,"applicationId" TEXT NOT NULL UNIQUE,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Message" ("id" TEXT PRIMARY KEY,"conversationId" TEXT NOT NULL,"senderId" TEXT NOT NULL,"body" TEXT NOT NULL,"readAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Notification" ("id" TEXT PRIMARY KEY,"userId" TEXT NOT NULL,"type" TEXT NOT NULL,"title" TEXT NOT NULL,"body" TEXT NOT NULL,"link" TEXT,"readAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Subscription" ("id" TEXT PRIMARY KEY,"companyId" TEXT NOT NULL UNIQUE,"plan" "SubscriptionPlan" NOT NULL DEFAULT 'FREE',"status" "SubscriptionStatus" NOT NULL DEFAULT 'ACTIVE',"stripeCustomerId" TEXT,"stripeSubscriptionId" TEXT,"currentPeriodEnd" TIMESTAMP(3));
CREATE TABLE "WebhookEvent" ("id" TEXT PRIMARY KEY,"provider" TEXT NOT NULL,"externalId" TEXT NOT NULL,"payload" JSONB NOT NULL,"status" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "WebhookEvent_provider_externalId_key" UNIQUE("provider","externalId"));
CREATE TABLE "AuditLog" ("id" TEXT PRIMARY KEY,"companyId" TEXT,"actorId" TEXT,"action" TEXT NOT NULL,"entityType" TEXT NOT NULL,"entityId" TEXT NOT NULL,"metadata" JSONB,"requestId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "AiMatchResult" ("id" TEXT PRIMARY KEY,"applicationId" TEXT NOT NULL UNIQUE,"score" INTEGER NOT NULL,"matchedSkills" TEXT[] NOT NULL,"missingSkills" TEXT[] NOT NULL,"evidence" TEXT[] NOT NULL,"explanation" TEXT NOT NULL,"provider" TEXT NOT NULL,"updatedAt" TIMESTAMP(3) NOT NULL);

ALTER TABLE "AuthAccount" ADD FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Session" ADD FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "AuthToken" ADD FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "CandidateProfile" ADD FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "CandidateExperience" ADD FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "CandidateEducation" ADD FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Resume" ADD FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "CompanyMember" ADD FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE;
ALTER TABLE "CompanyMember" ADD FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Job" ADD FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE;
ALTER TABLE "JobSkill" ADD FOREIGN KEY ("jobId") REFERENCES "Job"("id") ON DELETE CASCADE;
ALTER TABLE "ScreeningQuestion" ADD FOREIGN KEY ("jobId") REFERENCES "Job"("id") ON DELETE CASCADE;
ALTER TABLE "SavedJob" ADD FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "SavedJob" ADD FOREIGN KEY ("jobId") REFERENCES "Job"("id") ON DELETE CASCADE;
ALTER TABLE "PipelineStage" ADD FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE;
ALTER TABLE "Application" ADD FOREIGN KEY ("jobId") REFERENCES "Job"("id") ON DELETE CASCADE;
ALTER TABLE "Application" ADD FOREIGN KEY ("candidateId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Application" ADD FOREIGN KEY ("resumeId") REFERENCES "Resume"("id");
ALTER TABLE "Application" ADD FOREIGN KEY ("pipelineStageId") REFERENCES "PipelineStage"("id");
ALTER TABLE "Application" ADD FOREIGN KEY ("assignedMemberId") REFERENCES "CompanyMember"("id") ON DELETE SET NULL;
ALTER TABLE "ApplicationAnswer" ADD FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE;
ALTER TABLE "ApplicationAnswer" ADD FOREIGN KEY ("questionId") REFERENCES "ScreeningQuestion"("id");
ALTER TABLE "StageHistory" ADD FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE;
ALTER TABLE "CandidateNote" ADD FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE;
ALTER TABLE "CandidateNote" ADD FOREIGN KEY ("authorId") REFERENCES "CompanyMember"("id");
ALTER TABLE "Tag" ADD FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE;
ALTER TABLE "ApplicationTag" ADD FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE;
ALTER TABLE "ApplicationTag" ADD FOREIGN KEY ("tagId") REFERENCES "Tag"("id") ON DELETE CASCADE;
ALTER TABLE "Interview" ADD FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE;
ALTER TABLE "InterviewParticipant" ADD FOREIGN KEY ("interviewId") REFERENCES "Interview"("id") ON DELETE CASCADE;
ALTER TABLE "InterviewParticipant" ADD FOREIGN KEY ("memberId") REFERENCES "CompanyMember"("id") ON DELETE CASCADE;
ALTER TABLE "Scorecard" ADD FOREIGN KEY ("interviewId") REFERENCES "Interview"("id") ON DELETE CASCADE;
ALTER TABLE "Scorecard" ADD FOREIGN KEY ("authorId") REFERENCES "CompanyMember"("id");
ALTER TABLE "Offer" ADD FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE;
ALTER TABLE "Conversation" ADD FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE;
ALTER TABLE "Conversation" ADD FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE;
ALTER TABLE "Message" ADD FOREIGN KEY ("conversationId") REFERENCES "Conversation"("id") ON DELETE CASCADE;
ALTER TABLE "Message" ADD FOREIGN KEY ("senderId") REFERENCES "User"("id");
ALTER TABLE "Notification" ADD FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
ALTER TABLE "Subscription" ADD FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE;
ALTER TABLE "AuditLog" ADD FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE SET NULL;
ALTER TABLE "AiMatchResult" ADD FOREIGN KEY ("applicationId") REFERENCES "Application"("id") ON DELETE CASCADE;

CREATE INDEX "Session_userId_expiresAt_idx" ON "Session"("userId","expiresAt");
CREATE INDEX "AuthToken_userId_purpose_expiresAt_idx" ON "AuthToken"("userId","purpose","expiresAt");
CREATE INDEX "CandidateExperience_userId_startsAt_idx" ON "CandidateExperience"("userId","startsAt");
CREATE INDEX "CandidateEducation_userId_startsAt_idx" ON "CandidateEducation"("userId","startsAt");
CREATE INDEX "Invitation_companyId_email_idx" ON "Invitation"("companyId","email");
CREATE INDEX "Job_status_publishedAt_idx" ON "Job"("status","publishedAt");
CREATE INDEX "Application_jobId_stage_createdAt_idx" ON "Application"("jobId","stage","createdAt");
CREATE INDEX "Message_conversationId_createdAt_idx" ON "Message"("conversationId","createdAt");
CREATE INDEX "Notification_userId_createdAt_idx" ON "Notification"("userId","createdAt");
CREATE INDEX "AuditLog_companyId_createdAt_idx" ON "AuditLog"("companyId","createdAt");
